variables:
  FILE: "rattrack"

build:
  image: adnrv/opencv
  script:
    # create build dir
    - mkdir build
    - cd build
    # build the project
    - qmake ../src
    - make
  artifacts:
    paths:
      - ./build/$FILE
  tags:
    - docker
